[profile.default]
solc_version = '0.8.28'
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 5000
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true
evm_version="cancun"

via_ir = true
fuzz_runs = 50
deny_warnings = false

[fuzz]
seed = "0x3ff7210ab8230ac90b0bf938531e8fa25478d9f0272178a006ea726c64671798"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[fmt]
line_length = 160
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
ignore = ["libs/*","*.t.sol"]

[etherscan]
sepolia = { key = "", url = "https://eth-sepolia.public.blastapi.io" }